export const GET_CONTENTS_REQUEST = 'Home/GET_CONTENTS_REQUEST';
export const GET_CONTENTS_SUCCESS = 'Home/GET_CONTENTS_SUCCESS';
export const GET_CONTENTS_ERROR = 'Home/GET_CONTENTS_ERROR';

export const SAVE_CONTENTS_REQUEST = 'Home/SAVE_CONTENTS_REQUEST';
export const SAVE_CONTENTS_SUCCESS = 'Home/SAVE_CONTENTS_SUCCESS';
export const SAVE_CONTENTS_ERROR = 'Home/SAVE_CONTENTS_ERROR';

export const SET_CONTENTS_DATA = 'Home/SET_CONTENTS_DATA';



